name: ephys
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - statsmodels
  - openpyxl
  - jupyter
  - ipykernel
  - pip
  - pip:
      - pyabf
      - pingouin
      - statannotations
